# Optional Theme
# Helix Main Config File
theme = "solarized_dark"
# theme = "onedark"

[keys.normal]
"C-o" = ":config-open"
"A-s" = [":format", ":w"]
"A-q" = ":q"
"C-r" = ":config-reload"
"X" = ["extend_line_up", "extend_to_line_bounds"]
"A-p" = [":w", ":format", ":sh py %{buffer_name}"]
"A-r" = ":sh cargo run -q"
"C-e" = [":sh start /wait yazi",":redraw"]
"C-y" = ':sh  C:\\Users\\vitka\\AppData\\Local\\Yandex\\YandexBrowser\\Application\\browser.exe https://yandex.ru/search/?text=%{selection}'
"C-u" = ':sh  C:\\Users\\vitka\\AppData\\Local\\Yandex\\YandexBrowser\\Application\\browser.exe %{selection}'
"S-j" = "scroll_down"
"S-k" = "scroll_up"
S-tab = "move_parent_node_start"
tab = "move_parent_node_end"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.space.g]
"s" = ":sh git status"
"l" = ":sh git log"
"i" = ":sh git add -u"
"c" = ":sh git commit --allow-empty-message --no-edit"
"minus" = ":sh git stash"
"=" = ":sh git stash pop"
"+" = ":sh git stash drop"
"p" = ":sh git push -u"
"r" = ":sh git restore --staged ."
"R" = ":sh git restore ."

[keys.normal.space]
r = ":reload-all"

[editor.smart-tab]
supersede-menu = false

[editor]
line-number = "absolute"
mouse = false
true-color =  true
auto-completion = true
auto-pairs = true
auto-format = true
completion-trigger-len = 1  # Start showing completions after 1 character
path-completion = true
bufferline = "always"
default-line-ending = "native"
insert-final-newline = true
popup-border = "none"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = false
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true
# display-progress-messages = true


[editor.auto-save]
focus-lost = false
after-delay.enable = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.indent-guides]
character = "|"
render = true

[keys.normal.g]
a = "code_action" # Maps `ga` to show possible code actions

[keys.normal.space.space]
# b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
b = ":sh git blame %{buffer_name}"
d = ":sh git diff HEAD~1"

[editor.file-picker]
# file picker is handy
hidden = false
parents = true
 
